database:
  #types: mysql, sqlite
  type: 'sqlite'
  ip: 'localhost:3306'
  db: 'test'
  user: 'root'
  password: ''
  table: 'mostWanted'

general:
  # Minimum price for /contract <player> <price>
  minimum-price: 1000